//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.11 at 05:40:03 PM SGT 
//


package com.bms.eai.module.api.config.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bms.eai.module.api.config.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HostName_QNAME = new QName("", "hostName");
    private final static QName _PortNo_QNAME = new QName("", "portNo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bms.eai.module.api.config.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BmsModules }
     * 
     */
    public BmsModules createBmsModules() {
        return new BmsModules();
    }

    /**
     * Create an instance of {@link PropertyDetails }
     * 
     */
    public PropertyDetails createPropertyDetails() {
        return new PropertyDetails();
    }

    /**
     * Create an instance of {@link PdServerDetails }
     * 
     */
    public PdServerDetails createPdServerDetails() {
        return new PdServerDetails();
    }

    /**
     * Create an instance of {@link PropertyMaster }
     * 
     */
    public PropertyMaster createPropertyMaster() {
        return new PropertyMaster();
    }

    /**
     * Create an instance of {@link PmBusinessApiConfig }
     * 
     */
    public PmBusinessApiConfig createPmBusinessApiConfig() {
        return new PmBusinessApiConfig();
    }

    /**
     * Create an instance of {@link PmOperations }
     * 
     */
    public PmOperations createPmOperations() {
        return new PmOperations();
    }

    /**
     * Create an instance of {@link PropertyBlockDetails }
     * 
     */
    public PropertyBlockDetails createPropertyBlockDetails() {
        return new PropertyBlockDetails();
    }

    /**
     * Create an instance of {@link PbdBusinessApiConfig }
     * 
     */
    public PbdBusinessApiConfig createPbdBusinessApiConfig() {
        return new PbdBusinessApiConfig();
    }

    /**
     * Create an instance of {@link PbdOperations }
     * 
     */
    public PbdOperations createPbdOperations() {
        return new PbdOperations();
    }

    /**
     * Create an instance of {@link PropertyParkingBaySetup }
     * 
     */
    public PropertyParkingBaySetup createPropertyParkingBaySetup() {
        return new PropertyParkingBaySetup();
    }

    /**
     * Create an instance of {@link PpbsBusinessApiConfig }
     * 
     */
    public PpbsBusinessApiConfig createPpbsBusinessApiConfig() {
        return new PpbsBusinessApiConfig();
    }

    /**
     * Create an instance of {@link PpbsOperations }
     * 
     */
    public PpbsOperations createPpbsOperations() {
        return new PpbsOperations();
    }

    /**
     * Create an instance of {@link PropertyFacilitiesSetup }
     * 
     */
    public PropertyFacilitiesSetup createPropertyFacilitiesSetup() {
        return new PropertyFacilitiesSetup();
    }

    /**
     * Create an instance of {@link PfsBusinessApiConfig }
     * 
     */
    public PfsBusinessApiConfig createPfsBusinessApiConfig() {
        return new PfsBusinessApiConfig();
    }

    /**
     * Create an instance of {@link PfsOperations }
     * 
     */
    public PfsOperations createPfsOperations() {
        return new PfsOperations();
    }

    /**
     * Create an instance of {@link PropertyFixedAnnualRecurrings }
     * 
     */
    public PropertyFixedAnnualRecurrings createPropertyFixedAnnualRecurrings() {
        return new PropertyFixedAnnualRecurrings();
    }

    /**
     * Create an instance of {@link PfarBusinessApiConfig }
     * 
     */
    public PfarBusinessApiConfig createPfarBusinessApiConfig() {
        return new PfarBusinessApiConfig();
    }

    /**
     * Create an instance of {@link PfarOperations }
     * 
     */
    public PfarOperations createPfarOperations() {
        return new PfarOperations();
    }

    /**
     * Create an instance of {@link PropertyFinancialYear }
     * 
     */
    public PropertyFinancialYear createPropertyFinancialYear() {
        return new PropertyFinancialYear();
    }

    /**
     * Create an instance of {@link PfyBusinessApiConfig }
     * 
     */
    public PfyBusinessApiConfig createPfyBusinessApiConfig() {
        return new PfyBusinessApiConfig();
    }

    /**
     * Create an instance of {@link PfyOperations }
     * 
     */
    public PfyOperations createPfyOperations() {
        return new PfyOperations();
    }

    /**
     * Create an instance of {@link PropertyServiceProvider }
     * 
     */
    public PropertyServiceProvider createPropertyServiceProvider() {
        return new PropertyServiceProvider();
    }

    /**
     * Create an instance of {@link PspBusinessApiConfig }
     * 
     */
    public PspBusinessApiConfig createPspBusinessApiConfig() {
        return new PspBusinessApiConfig();
    }

    /**
     * Create an instance of {@link PspOperations }
     * 
     */
    public PspOperations createPspOperations() {
        return new PspOperations();
    }

    /**
     * Create an instance of {@link PropertyAsset }
     * 
     */
    public PropertyAsset createPropertyAsset() {
        return new PropertyAsset();
    }

    /**
     * Create an instance of {@link PaBusinessApiConfig }
     * 
     */
    public PaBusinessApiConfig createPaBusinessApiConfig() {
        return new PaBusinessApiConfig();
    }

    /**
     * Create an instance of {@link PaOperations }
     * 
     */
    public PaOperations createPaOperations() {
        return new PaOperations();
    }

    /**
     * Create an instance of {@link HumanResourceDetails }
     * 
     */
    public HumanResourceDetails createHumanResourceDetails() {
        return new HumanResourceDetails();
    }

    /**
     * Create an instance of {@link CommonModule }
     * 
     */
    public CommonModule createCommonModule() {
        return new CommonModule();
    }

    /**
     * Create an instance of {@link CmServerDetails }
     * 
     */
    public CmServerDetails createCmServerDetails() {
        return new CmServerDetails();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link StateBusinessApiConfig }
     * 
     */
    public StateBusinessApiConfig createStateBusinessApiConfig() {
        return new StateBusinessApiConfig();
    }

    /**
     * Create an instance of {@link StateOperations }
     * 
     */
    public StateOperations createStateOperations() {
        return new StateOperations();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link CountryBusinessApiConfig }
     * 
     */
    public CountryBusinessApiConfig createCountryBusinessApiConfig() {
        return new CountryBusinessApiConfig();
    }

    /**
     * Create an instance of {@link CountryOperations }
     * 
     */
    public CountryOperations createCountryOperations() {
        return new CountryOperations();
    }

    /**
     * Create an instance of {@link PropType }
     * 
     */
    public PropType createPropType() {
        return new PropType();
    }

    /**
     * Create an instance of {@link PropTypeBusinessApiConfig }
     * 
     */
    public PropTypeBusinessApiConfig createPropTypeBusinessApiConfig() {
        return new PropTypeBusinessApiConfig();
    }

    /**
     * Create an instance of {@link PropTypeOperations }
     * 
     */
    public PropTypeOperations createPropTypeOperations() {
        return new PropTypeOperations();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hostName")
    public JAXBElement<String> createHostName(String value) {
        return new JAXBElement<String>(_HostName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "portNo")
    public JAXBElement<String> createPortNo(String value) {
        return new JAXBElement<String>(_PortNo_QNAME, String.class, null, value);
    }

}
