//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.11 at 05:40:03 PM SGT 
//


package com.bms.eai.module.api.config.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}pdServerDetails"/&gt;
 *         &lt;element ref="{}propertyMaster"/&gt;
 *         &lt;element ref="{}propertyBlockDetails"/&gt;
 *         &lt;element ref="{}propertyParkingBaySetup"/&gt;
 *         &lt;element ref="{}propertyFacilitiesSetup"/&gt;
 *         &lt;element ref="{}propertyFixedAnnualRecurrings"/&gt;
 *         &lt;element ref="{}propertyFinancialYear"/&gt;
 *         &lt;element ref="{}propertyServiceProvider"/&gt;
 *         &lt;element ref="{}propertyAsset"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pdServerDetails",
    "propertyMaster",
    "propertyBlockDetails",
    "propertyParkingBaySetup",
    "propertyFacilitiesSetup",
    "propertyFixedAnnualRecurrings",
    "propertyFinancialYear",
    "propertyServiceProvider",
    "propertyAsset"
})
@XmlRootElement(name = "propertyDetails")
public class PropertyDetails
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected PdServerDetails pdServerDetails;
    @XmlElement(required = true)
    protected PropertyMaster propertyMaster;
    @XmlElement(required = true)
    protected PropertyBlockDetails propertyBlockDetails;
    @XmlElement(required = true)
    protected PropertyParkingBaySetup propertyParkingBaySetup;
    @XmlElement(required = true)
    protected PropertyFacilitiesSetup propertyFacilitiesSetup;
    @XmlElement(required = true)
    protected PropertyFixedAnnualRecurrings propertyFixedAnnualRecurrings;
    @XmlElement(required = true)
    protected PropertyFinancialYear propertyFinancialYear;
    @XmlElement(required = true)
    protected PropertyServiceProvider propertyServiceProvider;
    @XmlElement(required = true)
    protected PropertyAsset propertyAsset;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the pdServerDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PdServerDetails }
     *     
     */
    public PdServerDetails getPdServerDetails() {
        return pdServerDetails;
    }

    /**
     * Sets the value of the pdServerDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PdServerDetails }
     *     
     */
    public void setPdServerDetails(PdServerDetails value) {
        this.pdServerDetails = value;
    }

    /**
     * Gets the value of the propertyMaster property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyMaster }
     *     
     */
    public PropertyMaster getPropertyMaster() {
        return propertyMaster;
    }

    /**
     * Sets the value of the propertyMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyMaster }
     *     
     */
    public void setPropertyMaster(PropertyMaster value) {
        this.propertyMaster = value;
    }

    /**
     * Gets the value of the propertyBlockDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyBlockDetails }
     *     
     */
    public PropertyBlockDetails getPropertyBlockDetails() {
        return propertyBlockDetails;
    }

    /**
     * Sets the value of the propertyBlockDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyBlockDetails }
     *     
     */
    public void setPropertyBlockDetails(PropertyBlockDetails value) {
        this.propertyBlockDetails = value;
    }

    /**
     * Gets the value of the propertyParkingBaySetup property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyParkingBaySetup }
     *     
     */
    public PropertyParkingBaySetup getPropertyParkingBaySetup() {
        return propertyParkingBaySetup;
    }

    /**
     * Sets the value of the propertyParkingBaySetup property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyParkingBaySetup }
     *     
     */
    public void setPropertyParkingBaySetup(PropertyParkingBaySetup value) {
        this.propertyParkingBaySetup = value;
    }

    /**
     * Gets the value of the propertyFacilitiesSetup property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyFacilitiesSetup }
     *     
     */
    public PropertyFacilitiesSetup getPropertyFacilitiesSetup() {
        return propertyFacilitiesSetup;
    }

    /**
     * Sets the value of the propertyFacilitiesSetup property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyFacilitiesSetup }
     *     
     */
    public void setPropertyFacilitiesSetup(PropertyFacilitiesSetup value) {
        this.propertyFacilitiesSetup = value;
    }

    /**
     * Gets the value of the propertyFixedAnnualRecurrings property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyFixedAnnualRecurrings }
     *     
     */
    public PropertyFixedAnnualRecurrings getPropertyFixedAnnualRecurrings() {
        return propertyFixedAnnualRecurrings;
    }

    /**
     * Sets the value of the propertyFixedAnnualRecurrings property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyFixedAnnualRecurrings }
     *     
     */
    public void setPropertyFixedAnnualRecurrings(PropertyFixedAnnualRecurrings value) {
        this.propertyFixedAnnualRecurrings = value;
    }

    /**
     * Gets the value of the propertyFinancialYear property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyFinancialYear }
     *     
     */
    public PropertyFinancialYear getPropertyFinancialYear() {
        return propertyFinancialYear;
    }

    /**
     * Sets the value of the propertyFinancialYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyFinancialYear }
     *     
     */
    public void setPropertyFinancialYear(PropertyFinancialYear value) {
        this.propertyFinancialYear = value;
    }

    /**
     * Gets the value of the propertyServiceProvider property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyServiceProvider }
     *     
     */
    public PropertyServiceProvider getPropertyServiceProvider() {
        return propertyServiceProvider;
    }

    /**
     * Sets the value of the propertyServiceProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyServiceProvider }
     *     
     */
    public void setPropertyServiceProvider(PropertyServiceProvider value) {
        this.propertyServiceProvider = value;
    }

    /**
     * Gets the value of the propertyAsset property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyAsset }
     *     
     */
    public PropertyAsset getPropertyAsset() {
        return propertyAsset;
    }

    /**
     * Sets the value of the propertyAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyAsset }
     *     
     */
    public void setPropertyAsset(PropertyAsset value) {
        this.propertyAsset = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
